<?php
/**
 * Created by PhpStorm.
 * User: chungtran
 * Date: 25/01/2019
 * Time: 11:39
 */
include_once 'Circle.php';

class Cylinder extends Circle
{
    public $height;

    public function __construct($radius, $color, $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    public function getVolume()
    {
        return parent::getArea() * $this->height;
    }

public function __toString()
{
    return "My Cylinder:{ Area = " . $this->getArea() . " Volume = " . $this->getVolume() . "}"; // TODO: Change the autogenerated stub
}
}